### ISSUE TITLE
Add support for cloud-init for each Linux distribution

### ISSUE THREAD

**Issue by tenthirtyam** [vmware-samples/packer-examples-for-vsphere#691]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Add support for cloud-init for each Linux distribution, where applicable, by default with an option for guest tools override.

Note: Not all may support the cloud-init release with the VMware datasource.

### Use Case(s)

Add support for cloud-init for each Linux distribution, where applicable, by default with an option for guest tools override.

### Potential Configuration

```yaml
- name: Configuring cloud-init.
  become: true
  tasks:
    - name: Add cloud-init configuration
      copy:
        content: |
          disable_vmware_customization: false
          datasource:
            VMware:
              vmware_cust_file_max_wait: 20
        dest: /etc/cloud/cloud.cfg.d/99-vmware-guest-customization.cfg

    - name: Enable SSH password authentication in cloud-init configuration.
      lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: '^ssh_pwauth:'
        line: 'ssh_pwauth: 1'
```

However, dependent on the OS.

**Comment by burnsjared0415** [comment]
will pick

**Comment by tenthirtyam** [comment]
- [x] Photon OS 4: #900
- [x] Photon OS 5: #900
- [x] Debian 12: #883
- [x] Debian 11: _Not Implementing_
- [x] Ubuntu Server 24.04: #843
- [x] Ubuntu Server 22.04: #843
- [x] Ubuntu Server 20.04: #843
- [x] Red Hat Enterprise Linux 9: #888
- [x] Red Hat Enterprise Linux 8: #888 
- [x] Red Hat Enterprise Linux 7: _Not Implementing_
- [x] Rocky Linux 9: #895
- [x] Rocky Linux 8: #895
- [x] AlmaLinux OS 9: #898
- [x] AlmaLinux OS 8: #898
- [x] Oracle Linux 9: #899
- [x] Oracle Linux 8:#899
- [x] CentOS Stream 9: #897
- [x] CentOS Stream 8: #897
- [x] CentOS 7: _Not Implementing_
- [x] Fedora Server: #892 
- [x] SUSE Enterprise Linux: #919

**Comment by tenthirtyam** [comment]
Completed for the next release!
